# Generated by Django 5.0 on 2023-12-13 17:11

import appcore.services.gen_token
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "access_token",
                    models.TextField(
                        default=appcore.services.gen_token.gen_token, max_length=255
                    ),
                ),
                ("access_token_created", models.DateTimeField(auto_now_add=True)),
                ("expires_in", models.IntegerField(default=86400)),
                (
                    "refresh_token",
                    models.TextField(
                        default=appcore.services.gen_token.gen_token,
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("refresh_token_created", models.DateTimeField(auto_now_add=True)),
                ("refresh_token_expires_in", models.IntegerField(default=525600)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(default="", max_length=255)),
                ("last_name", models.CharField(default="", max_length=255)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("m", "Male"),
                            ("f", "Female"),
                            ("n", "Non-binary"),
                            ("o", "Other"),
                        ],
                        default=None,
                        null=True,
                    ),
                ),
                ("dob", models.DateField(default=None, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
