# Generated by Django 5.0 on 2023-12-13 16:22

import appcore.services.gen_token
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appaccount", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "access_token",
                    models.TextField(
                        default=appcore.services.gen_token.gen_token, max_length=255
                    ),
                ),
                ("access_token_created", models.DateTimeField(auto_now_add=True)),
                ("expires_in", models.IntegerField(default=86400)),
                (
                    "refresh_token",
                    models.TextField(
                        default=appcore.services.gen_token.gen_token, max_length=255
                    ),
                ),
                ("refresh_token_created", models.DateTimeField(auto_now_add=True)),
                ("refresh_token_expires_in", models.IntegerField(default=525600)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
