# Generated by Django 5.0 on 2023-12-13 17:04

import appcore.services.gen_token
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appaccount", "0003_alter_userprofile_gender_delete_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="refresh_token",
            field=models.TextField(
                default=appcore.services.gen_token.gen_token,
                max_length=255,
                unique=True,
            ),
        ),
    ]
