/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/account/auths/login/": {
    /**
     * Post Login
     * @description Login through API. It creates a session, and a user if not exist.
     */
    post: operations["appaccount_routes_auths_post_login"];
  };
  "/api/account/auths/logout/": {
    /**
     * Post Logout
     * @description Logout given access_token, session is destroyed.
     */
    post: operations["appaccount_routes_auths_post_logout"];
  };
  "/api/account/auths/refresh/": {
    /**
     * Post Refresh
     * @description Refresh access_token using refresh_token.
     */
    post: operations["appaccount_routes_auths_post_refresh"];
  };
  "/api/account/users/me/": {
    /**
     * Get Me
     * @description Get current user profile
     * gender can be one of:
     * ```
     * "m": "Male",
     * "f": "Female",
     * "n": "Non-binary",
     * "o": "Other",
     * ```
     */
    get: operations["appaccount_routes_users_get_me"];
    /**
     * Patch Me
     * @description Patch current user profile
     * gender can be one of:
     * ```
     * "m": "Male",
     * "f": "Female",
     * "n": "Non-binary",
     * "o": "Other",
     * ```
     */
    patch: operations["appaccount_routes_users_patch_me"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** LoginPostOut */
    LoginPostOut: {
      /** Access Token */
      access_token: string;
      /** Expires In */
      expires_in: number;
      /** Refresh Token */
      refresh_token: string;
      /** Refresh Token Expires In */
      refresh_token_expires_in: number;
    };
    /** LoginPostIn */
    LoginPostIn: {
      /**
       * Email
       * Format: email
       */
      email: string;
    };
    /** RefreshPostOut */
    RefreshPostOut: {
      /** Access Token */
      access_token: string;
      /** Expires In */
      expires_in: number;
      /** Refresh Token */
      refresh_token: string;
    };
    /** RefreshPostIn */
    RefreshPostIn: {
      /** Refresh Token */
      refresh_token: string;
    };
    /** MeGetOut */
    MeGetOut: {
      /**
       * Created
       * Format: date-time
       */
      created: string;
      /**
       * Updated
       * Format: date-time
       */
      updated: string;
      /**
       * First Name
       * @default
       */
      first_name?: string;
      /**
       * Last Name
       * @default
       */
      last_name?: string;
      /** Gender */
      gender?: string | null;
      /** Dob */
      dob?: string | null;
      /** Username */
      username: string;
    };
    /** MePatchOut */
    MePatchOut: {
      /**
       * Created
       * Format: date-time
       */
      created: string;
      /**
       * Updated
       * Format: date-time
       */
      updated: string;
      /**
       * First Name
       * @default
       */
      first_name?: string;
      /**
       * Last Name
       * @default
       */
      last_name?: string;
      /** Gender */
      gender?: string | null;
      /** Dob */
      dob?: string | null;
      /** Username */
      username: string;
    };
    /** MePatchIn */
    MePatchIn: {
      /**
       * First Name
       * @default
       */
      first_name?: string;
      /**
       * Last Name
       * @default
       */
      last_name?: string;
      /** Gender */
      gender?: string | null;
      /** Dob */
      dob?: string | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * Post Login
   * @description Login through API. It creates a session, and a user if not exist.
   */
  appaccount_routes_auths_post_login: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginPostIn"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["LoginPostOut"];
        };
      };
    };
  };
  /**
   * Post Logout
   * @description Logout given access_token, session is destroyed.
   */
  appaccount_routes_auths_post_logout: {
    responses: {
      /** @description No Content */
      204: {
        content: never;
      };
    };
  };
  /**
   * Post Refresh
   * @description Refresh access_token using refresh_token.
   */
  appaccount_routes_auths_post_refresh: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["RefreshPostIn"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["RefreshPostOut"];
        };
      };
      /** @description Unauthorized */
      401: {
        content: never;
      };
    };
  };
  /**
   * Get Me
   * @description Get current user profile
   * gender can be one of:
   * ```
   * "m": "Male",
   * "f": "Female",
   * "n": "Non-binary",
   * "o": "Other",
   * ```
   */
  appaccount_routes_users_get_me: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["MeGetOut"];
        };
      };
    };
  };
  /**
   * Patch Me
   * @description Patch current user profile
   * gender can be one of:
   * ```
   * "m": "Male",
   * "f": "Female",
   * "n": "Non-binary",
   * "o": "Other",
   * ```
   */
  appaccount_routes_users_patch_me: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["MePatchIn"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["MePatchOut"];
        };
      };
    };
  };
}
